"""MTEB task-name -> task-family taxonomy for the ``mteb_*`` fetchers.

Source of truth: ``embeddings-benchmark/mteb`` (mteb==2.21.8) task metadata
names, extracted per task-type folder from the published wheel. The HF
``mteb/results`` dataset tags every row with a raw ``task_name`` (e.g.
``"Banking77Classification"``, ``"ArguAna"``, ``"STS22"``) but carries no
task-type column, so family classification is name-based:

1. exact match against the sets below (canonical for known tasks, covering
   the many names that do not follow a suffix convention, e.g. ``ArguAna``,
   ``BIOSSES``, ``AskUbuntuDupQuestions``);
2. suffix/prefix fallback for task names added to newer MTEB versions after
   this table was generated (``*Classification``, ``*Reranking``,
   ``*Retrieval``, ``*RetrievalHardNegatives``, ``STS*``/``*STS``);
3. ``None`` -> the row is ignored (clustering, pair classification,
   summarization, bitext mining, ... are outside the four supported
   families).

Regenerate the exact-match sets with mteb installed::

    python - <<'PY'
    import mteb, json
    from mteb.get_tasks import MTEBTaskList  # noqa
    PY
    # or: walk mteb/tasks/<type>/*.py and collect TaskMetadata(name=...)

Unknown-name handling is fail-open by design: a newer dataset with task
names this table does not know only loses those rows, never crashes. The
suffix fallback also covers the ``XRetrievalHardNegatives`` hard-negatives
variants present in the dataset but absent from mteb 2.21.8.
"""

from __future__ import annotations

CLASSIFICATION_TASKS: tuple[str, ...] = (
    "AESDD",
    "AJGT",
    "AVEDatasetClassification",
    "AVMemeAudioVideoClassification",
    "AfriHateClassification",
    "AfriSentiClassification",
    "AfriSentiLangClassification",
    "AmazonCounterfactualClassification",
    "AmazonCounterfactualVNClassification",
    "AmazonPolarityClassification",
    "AmazonPolarityVNClassification",
    "AmazonReviewsClassification",
    "AmazonReviewsVNClassification",
    "AmbientAcousticContext",
    "AngryTweetsClassification",
    "ArxivClassification",
    "Banking77Classification",
    "Banking77VNClassification",
    "BeehiveStatesClassification",
    "BeijingOpera",
    "BengaliDocumentClassification",
    "BengaliHateSpeechClassification",
    "BengaliSentimentAnalysis",
    "BirdCLEF",
    "Birdsnap",
    "BreakfastClassification",
    "BulgarianStoreReviewSentimentClassfication",
    "CAMEOEmotionClassification",
    "CBD",
    "CIFAR10",
    "CREMA_D",
    "CSFDCZMovieReviewSentimentClassification",
    "CSFDSKMovieReviewSentimentClassification",
    "CSTRVCTKAccentID",
    "CSTRVCTKGender",
    "Caltech101",
    "CanadaTaxCourtOutcomesLegalBenchClassification",
    "CataloniaTweetClassification",
    "CommonLanguageAgeDetection",
    "CommonLanguageGenderDetection",
    "CommonLanguageLanguageDetection",
    "Country211",
    "CrisisMMDInformativeClassification",
    "CyrillicTurkicLangClassification",
    "CzechProductReviewSentimentClassification",
    "CzechSoMeSentimentClassification",
    "CzechSubjectivityClassification",
    "DBpediaClassification",
    "DKHateClassification",
    "DTD",
    "DadoEvalCoarseClassification",
    "DalajClassification",
    "DanishPoliticalCommentsClassification",
    "Ddisco",
    "Diving48Classification.V1",
    "DutchBookReviewSentimentClassification",
    "DutchColaClassification",
    "DutchGovernmentBiasClassification",
    "DutchNewsArticlesClassification",
    "DutchSarcasticHeadlinesClassification",
    "ESC50",
    "EmotionClassification",
    "EmotionVNClassification",
    "EstonianValenceClassification",
    "EuroSAT",
    "ExpressoRead",
    "FER2013",
    "FGVCAircraft",
    "FSDD",
    "FSDKaggle2018Classification",
    "FilipinoHateSpeechClassification",
    "FilipinoShopeeReviewsClassification",
    "FinToxicityClassification",
    "FinancialPhrasebankClassification",
    "Food101Classification",
    "FrenchBookReviews",
    "FrenkEnClassification",
    "FrenkHrClassification",
    "FrenkSlClassification",
    "GLOBEV2Age",
    "GLOBEV2Gender",
    "GLOBEV3Age",
    "GLOBEV3Gender",
    "GTZANGenre",
    "GeoreviewClassification",
    "GeorgianSentimentClassification",
    "GermanPoliticiansTwitterSentimentClassification",
    "GreekLegalCodeClassification",
    "GujaratiNewsClassification",
    "GunshotTriangulation",
    "HMDB51Classification",
    "HUMEEmotionClassification",
    "HUMEMultilingualSentimentClassification",
    "HUMEToxicConversationsClassification",
    "HUMETweetSentimentExtractionClassification",
    "HateSpeechPortugueseClassification",
    "HeadlineClassification",
    "HebrewSentimentAnalysis",
    "HinDialectClassification",
    "HindiDiscourseClassification",
    "HotelReviewSentimentClassification",
    "HumanAnimalCartoonVA",
    "IEMOCAPEmotion",
    "IEMOCAPGender",
    "INatSounds",
    "IconclassClassification",
    "Imagenet1k",
    "ImdbClassification",
    "ImdbVNClassification",
    "InappropriatenessClassification",
    "IndicLangClassification",
    "IndicNLPNewsClassification",
    "IndicSentimentClassification",
    "IndonesianIdClickbaitClassification",
    "IndonesianMongabayConservationClassification",
    "InjongoIntent",
    "IsiZuluNewsClassification",
    "ItaCaseholdClassification",
    "Itacola",
    "JapaneseSentimentClassification",
    "JavaneseIMDBClassification",
    "KLUE-TC",
    "KannadaNewsClassification",
    "KinNewsClassification",
    "Kinetics400VA",
    "Kinetics600VA",
    "Kinetics700VA",
    "KinopoiskClassification",
    "KorFin",
    "KorHateClassification",
    "KorSarcasmClassification",
    "KurdishSentimentClassification",
    "LanguageClassification",
    "LccSentimentClassification",
    "LibriCount",
    "MELDAudioVideoClassification",
    "MInDS14",
    "MNIST",
    "MTOPDomainClassification",
    "MTOPDomainVNClassification",
    "MTOPIntentClassification",
    "MTOPIntentVNClassification",
    "MacedonianTweetSentimentClassification",
    "MalayalamNewsClassification",
    "MarathiNewsClassification",
    "MasakhaNEWSClassification",
    "MassiveIntentClassification",
    "MassiveIntentVNClassification",
    "MassiveScenarioClassification",
    "MassiveScenarioVNClassification",
    "Moroco",
    "MovieReviewSentimentClassification",
    "MridinghamStroke",
    "MridinghamTonic",
    "MultiEupSlovakPartyClassification",
    "MultiHateClassification",
    "MultilingualSentimentClassification",
    "MusicAVQACLSAudioVideoClassification",
    "MyanmarNews",
    "NSynth",
    "NaijaSenti",
    "NepaliNewsClassification",
    "NewsClassification",
    "NoRecClassification",
    "NordicLangClassification",
    "NorwegianParliamentClassification",
    "NusaParagraphEmotionClassification",
    "NusaParagraphTopicClassification",
    "NusaX-senti",
    "OdiaNewsClassification",
    "OnlineStoreReviewSentimentClassification",
    "OpenTenderClassification",
    "OxfordFlowersClassification",
    "OxfordPets",
    "PatentClassification",
    "PersianFoodSentimentClassification",
    "PoemSentimentClassification",
    "PunjabiNewsClassification",
    "RAVDESSAVClassification",
    "RESISC45",
    "RestaurantReviewSentimentClassification",
    "RomanianReviewsSentiment",
    "RomanianSentimentClassification",
    "RuNLUIntentClassification",
    "RuReviewsClassification",
    "RuSciBenchCoreRiscClassification",
    "RuSciBenchGRNTIClassification",
    "RuSciBenchOECDClassification",
    "RuToxicOKMLCUPClassification",
    "SDSEyeProtectionClassification",
    "SDSGlovesClassification",
    "SIB200Classification",
    "SIBFLEURS",
    "STL10",
    "SUN397",
    "SanskritShlokasClassification",
    "SardiStanceClassification",
    "ScalaClassification",
    "ScandiSentClassification",
    "SciRepEvalBiomimicryClassification",
    "SciRepEvalDRSMClassification",
    "SciRepEvalMeSHDescriptorsClassification",
    "SentiRuEval2016",
    "SentimentAnalysisHindi",
    "SinhalaNewsClassification",
    "SinhalaNewsSourceClassification",
    "SiswatiNewsClassification",
    "SlovakHateSpeechClassification",
    "SlovakMovieReviewSentimentClassification",
    "SlovakParlaSentClassification",
    "SomethingSomethingV2Classification",
    "SouthAfricanLangClassification",
    "SpanishNewsClassification",
    "SpanishSentimentClassification",
    "SpeechCommands",
    "SpokeNEnglish",
    "SpokenQAForIC",
    "StanfordCars",
    "SwahiliNewsClassification",
    "SweRecClassification",
    "SwedishSentimentClassification",
    "SwissJudgementClassification",
    "SynPerChatbotConvSAAnger",
    "TAUAcousticScenes2022Mobile",
    "TNews",
    "TUTAcousticScenes",
    "TamilNewsClassification",
    "TeluguAndhraJyotiNewsClassification",
    "TenKGnadClassification",
    "ToxicChatClassification",
    "ToxicConversationsClassification",
    "ToxicConversationsVNClassification",
    "TswanaNewsClassification",
    "TurkicClassification",
    "TurkishMovieSentimentClassification",
    "TurkishProductSentimentClassification",
    "TweetEmotionClassification",
    "TweetSarcasmClassification",
    "TweetSentimentClassification",
    "TweetSentimentExtractionClassification",
    "TweetSentimentExtractionVNClassification",
    "TweetTopicSingleClassification",
    "UCF101",
    "UkrFormalityClassification",
    "UrbanSound8k",
    "UrduRomanSentimentClassification",
    "VGGSoundVA",
    "VaccinChatNLClassification",
    "VieStudentFeedbackClassification",
    "VocalSound",
    "VoxCelebSA",
    "VoxLingua107_Top10",
    "VoxPopuliAccentID",
    "VoxPopuliGenderID",
    "VoxPopuliLanguageID",
    "WRIMEClassification",
    "WikipediaBioMetChemClassification",
    "WikipediaBiolumNeurochemClassification",
    "WikipediaChemEngSpecialtiesClassification",
    "WikipediaChemFieldsClassification",
    "WikipediaChemistryTopicsClassification",
    "WikipediaCompChemSpectroscopyClassification",
    "WikipediaCryobiologySeparationClassification",
    "WikipediaCrystallographyAnalyticalClassification",
    "WikipediaGreenhouseEnantiopureClassification",
    "WikipediaIsotopesFissionClassification",
    "WikipediaLuminescenceClassification",
    "WikipediaOrganicInorganicClassification",
    "WikipediaSaltsSemiconductorsClassification",
    "WikipediaSolidStateColloidalClassification",
    "WikipediaTheoreticalAppliedClassification",
    "WisesightSentimentClassification",
    "WongnaiReviewsClassification",
    "WorldSenseAudioVideoClassification",
    "YahooAnswersTopicsClassification",
    "YelpReviewFullClassification",
    "YueOpenriceReviewClassification",
    "label",
    "text",
    "webp",
)

RETRIEVAL_TASKS: tuple[str, ...] = (
    "ABOI2VRetrieval",
    "ACMComposedAudioRetrieval",
    "ADVANCEA2IRetrieval",
    "AILACasedocs",
    "AILAStatutes",
    "ARCChallenge",
    "AVCapsA2TRetrieval",
    "AVMemeExamV2TRetrieval",
    "ActivityNetCaptionsV2TRetrieval",
    "AfriMCQAA2IRetrieval",
    "AlloprofRetrieval",
    "AlphaNLI",
    "AppsRetrieval",
    "ArguAna",
    "ArguAna-Fa",
    "ArguAna-NL",
    "ArguAna-PL",
    "ArguAna-VN",
    "AudioCapsA2TRetrieval",
    "AudioCapsAVV2TRetrieval",
    "AudioSetStrongA2TRetrieval",
    "AutoRAGRetrieval",
    "BIRCO-ArguAna",
    "BIRCO-ClinicalTrial",
    "BIRCO-DorisMae",
    "BIRCO-Relic",
    "BIRCO-WTB",
    "BLINKIT2IRetrieval",
    "BLINKIT2TRetrieval",
    "BSARDRetrieval",
    "BarExamQA",
    "BelebeleRetrieval",
    "BillSumCA",
    "BillSumUS",
    "BridgeV2VRetrieval",
    "BrightProBiologyRetrieval",
    "BrightRetrieval",
    "BrowseCompPlusRetrieval",
    "BuiltBenchRetrieval",
    "CASTELLAAMRRetrieval",
    "CIRRIT2IRetrieval",
    "CLDAT2ARetrieval",
    "CMUArcticA2TRetrieval",
    "COCOModalEquivT2IRetrieval",
    "COIRCodeSearchNetRetrieval",
    "CQADupstack-Wordpress-PL",
    "CQADupstackAndroid-NL",
    "CQADupstackAndroid-VN",
    "CQADupstackAndroidRetrieval",
    "CQADupstackEnglish-NL",
    "CQADupstackEnglishRetrieval",
    "CQADupstackGaming-NL",
    "CQADupstackGamingRetrieval",
    "CQADupstackGis-NL",
    "CQADupstackGis-VN",
    "CQADupstackGisRetrieval",
    "CQADupstackMathematica-NL",
    "CQADupstackMathematica-VN",
    "CQADupstackMathematicaRetrieval",
    "CQADupstackPhysics-NL",
    "CQADupstackPhysics-VN",
    "CQADupstackPhysicsRetrieval",
    "CQADupstackProgrammers-NL",
    "CQADupstackProgrammers-VN",
    "CQADupstackProgrammersRetrieval",
    "CQADupstackStats-NL",
    "CQADupstackStats-VN",
    "CQADupstackStatsRetrieval",
    "CQADupstackTex-NL",
    "CQADupstackTex-VN",
    "CQADupstackTexRetrieval",
    "CQADupstackUnix-NL",
    "CQADupstackUnix-VN",
    "CQADupstackUnixRetrieval",
    "CQADupstackWebmasters-NL",
    "CQADupstackWebmasters-VN",
    "CQADupstackWebmastersRetrieval",
    "CQADupstackWordpress-NL",
    "CQADupstackWordpress-VN",
    "CQADupstackWordpressRetrieval",
    "CUB200I2IRetrieval",
    "CUREv1",
    "CaReBenchT2VRetrieval",
    "ChatDoctorRetrieval",
    "ChemHotpotQARetrieval",
    "ChemNQRetrieval",
    "ChemRxivRetrieval",
    "ChinaOpenT2VRetrieval",
    "ClimateFEVER",
    "ClimateFEVER-NL",
    "ClimateFEVER-VN",
    "ClothoA2TRetrieval",
    "ClothoMomentRetrieval",
    "CoVRRVT2VRetrieval",
    "Code1Retrieval",
    "CodeEditSearchRetrieval",
    "CodeFeedbackMT",
    "CodeFeedbackST",
    "CodeRAGProgrammingSolutions",
    "CodeSearchNetCCRetrieval",
    "CodeSearchNetRetrieval",
    "CodeTransOceanContest",
    "CodeTransOceanDL",
    "CommonVoiceMini17A2TRetrieval",
    "CorebC2TRetrieval",
    "CosQA",
    "Covers80A2ARetrieval",
    "CrossLingualSemanticDiscriminationWMT19",
    "CrossLingualSemanticDiscriminationWMT21",
    "DAPFAMAllTitlAbsToTitlAbsRetrieval",
    "DBPedia",
    "DBPedia-NL",
    "DBPedia-PL",
    "DBPedia-VN",
    "DROIDIT2VRetrieval",
    "DS1000Retrieval",
    "DanFeverRetrieval",
    "DanRAGT2IRetrieval",
    "DenseWebVidCoVRVT2VRetrieval",
    "DiDeMoV2TRetrieval",
    "DutchNewsArticlesRetrieval",
    "EDIRIT2IRetrieval",
    "EDIST2ITRetrieval",
    "EMIDA2IRetrieval",
    "EPBench",
    "EVVERetrieval",
    "ElasticKBRetrieval",
    "EmoVDBA2TRetrieval",
    "EncyclopediaVQAIT2ITRetrieval",
    "EnglishFinance1Retrieval",
    "EnglishFinance2Retrieval",
    "EnglishFinance3Retrieval",
    "EnglishFinance4Retrieval",
    "EnglishHealthcare1Retrieval",
    "EstQA",
    "EuroPIRQRetrieval",
    "FEVER",
    "FEVER-NL",
    "FEVER-VN",
    "FGMCapsT2ARetrieval",
    "FLAREUnifiedT2VARetrieval",
    "FORBI2IRetrieval",
    "FQuADRetrieval",
    "FaithDial",
    "Fashion200kI2TRetrieval",
    "Fashion200kT2IRetrieval",
    "FashionIQIT2IRetrieval",
    "FeedbackQARetrieval",
    "FiQA-PL",
    "FiQA2018",
    "FiQA2018-NL",
    "FiQA2018-VN",
    "FinQARetrieval",
    "FinanceBenchRetrieval",
    "FleursA2TRetrieval",
    "Flickr30kI2TRetrieval",
    "Flickr30kT2IRetrieval",
    "FlickrAudioToImageRetrieval",
    "French1Retrieval",
    "FrenchLegal1Retrieval",
    "FreshStackRetrieval",
    "GLAMI1MT2IRetrieval",
    "GLDv2I2IRetrieval",
    "GLDv2I2TRetrieval",
    "GeorgianFAQRetrieval",
    "GerDaLIR",
    "GerDaLIRSmall",
    "German1Retrieval",
    "GermanDPR",
    "GermanGovServiceRetrieval",
    "GermanHealthcare1Retrieval",
    "GermanLegal1Retrieval",
    "GermanQuAD-Retrieval",
    "GigaSpeechA2TRetrieval",
    "GlobalNewsRetrieval",
    "GoogleSVQA2TRetrieval",
    "GovReport",
    "GreatestHitsA2VRetrieval",
    "GreekCivicsQA",
    "GreenNodeTableMarkdownRetrieval",
    "HC3FinanceRetrieval",
    "HagridRetrieval",
    "HatefulMemesI2TRetrieval",
    "HatefulMemesT2IRetrieval",
    "HellaSwag",
    "HiFiTTSA2TRetrieval",
    "HotpotQA",
    "HotpotQA-NL",
    "HotpotQA-PL",
    "HotpotQA-VN",
    "HumanEvalRetrieval",
    "HunSum2AbstractiveRetrieval",
    "IRPapersT2IRetrieval",
    "IRPapersT2ITRetrieval",
    "ImageCoDeT2IRetrieval",
    "IncompeBenchStrictRetrieval",
    "IndicQARetrieval",
    "InfoSeekIT2ITRetrieval",
    "InfoSeekIT2TRetrieval",
    "InsAVE80KVT2VRetrieval",
    "JLCorpusA2TRetrieval",
    "JaCWIRRetrieval",
    "JaCWIRRetrievalLite",
    "JaGovFaqsRetrieval",
    "JaQuADRetrieval",
    "JamAltArtistA2ARetrieval",
    "JapaneseCode1Retrieval",
    "JapaneseLegal1Retrieval",
    "JaqketRetrieval",
    "JaqketRetrievalLite",
    "JinaVDRMedicalPrescriptionsRetrieval",
    "JuriFindITRetrieval",
    "Ko-StrategyQA",
    "KoVidore2CybersecurityRetrieval",
    "LASSA2TRetrieval",
    "LEMBNarrativeQARetrieval",
    "LEMBNeedleRetrieval",
    "LEMBPasskeyRetrieval",
    "LEMBQMSumRetrieval",
    "LEMBSummScreenFDRetrieval",
    "LEMBWikimQARetrieval",
    "LIBEROI2VRetrieval",
    "LIMITRetrieval",
    "LLaVAIT2TRetrieval",
    "LPMusicCapsMTTA2TRetrieval",
    "LawIRKo",
    "LeCaRDv2",
    "LegalBenchConsumerContractsQA",
    "LegalBenchCorporateLobbying",
    "LegalQANLRetrieval",
    "LegalQuAD",
    "LegalSummarization",
    "LexRetrieval.v1",
    "LibriSpeechSpeakerA2ARetrieval",
    "LibriTTSA2TRetrieval",
    "LitSearchRetrieval",
    "LoTTE",
    "LombardGridA2VRetrieval",
    "MACSA2TRetrieval",
    "MBPPRetrieval",
    "METI2IRetrieval",
    "MIAOA2IRetrieval",
    "MIRACLJaRetrievalLite",
    "MIRACLRetrieval",
    "MIRACLVisionRetrieval",
    "MKQARetrieval",
    "MLQARetrieval",
    "MLQuestions",
    "MMBrightAcademiaT2TRetrieval",
    "MMDocIRT2IRetrieval",
    "MMDocIRT2ITRetrieval",
    "MMEditAT2ARetrieval",
    "MMLongBenchDocRetrieval",
    "MMarcoRetrievalMultilingual",
    "MSCOCOI2TRetrieval",
    "MSCOCOT2IRetrieval",
    "MSMARCO",
    "MSMARCO-PL",
    "MSMARCO-VN",
    "MSMARCOv2",
    "MSRVTTV2T",
    "MSVDT2VRetrieval",
    "MSVDV2TRetrieval",
    "ManiSkillI2VRetrieval",
    "MarsVLPairsT2IRetrieval",
    "MedicalQARetrieval",
    "MemotionI2TRetrieval",
    "MemotionT2IRetrieval",
    "MintakaRetrieval",
    "MomentSeekerTI2VRetrieval",
    "MovingFashionI2VRetrieval",
    "MrTidyRetrieval",
    "MrTyDiJaRetrievalLite",
    "MuPLeR-retrieval",
    "Multi30kT2IRetrieval",
    "MultiLongDocRetrieval",
    "MultilingualNanoArguAnaRetrieval",
    "MusicCapsA2TRetrieval",
    "NFCorpus",
    "NFCorpus-NL",
    "NFCorpus-PL",
    "NFCorpus-VN",
    "NIGHTSI2IRetrieval",
    "NLPJournalAbsArticleRetrieval.V2",
    "NLPJournalAbsIntroRetrieval.V2",
    "NLPJournalTitleAbsRetrieval.V2",
    "NLPJournalTitleIntroRetrieval.V2",
    "NQ",
    "NQ-NL",
    "NQ-PL",
    "NQ-VN",
    "NQTablesRetrieval",
    "NanoArguAnaRetrieval",
    "NanoClimateFeverRetrieval",
    "NanoDBPediaRetrieval",
    "NanoFEVERRetrieval",
    "NanoFiQA2018Retrieval",
    "NanoHotpotQARetrieval",
    "NanoMSMARCORetrieval",
    "NanoNFCorpusRetrieval",
    "NanoNQRetrieval",
    "NanoQuoraRetrieval",
    "NanoSCIDOCSRetrieval",
    "NanoSciFactRetrieval",
    "NanoTouche2020Retrieval",
    "NarrativeQARetrieval",
    "NayanaIRMonoBenchTamilRetrieval",
    "NeuCLIR2022Retrieval",
    "NeuCLIR2023Retrieval",
    "NorQuadRetrieval",
    "OBLIQBenchTwitterRetrieval",
    "OKVQAIT2TRetrieval",
    "OVENIT2ITRetrieval",
    "OVENIT2TRetrieval",
    "OmniWikiV2IRetrieval",
    "OmnilingualASRA2TRetrieval",
    "OpenTenderRetrieval",
    "PIQA",
    "PUGGRetrieval",
    "Panda70MV2TRetrieval",
    "PublicHealthQA",
    "Quail",
    "Quora-NL",
    "Quora-PL",
    "Quora-VN",
    "QuoraRetrieval",
    "RARbCode",
    "RARbMath",
    "RAVENEAI2TRetrieval",
    "ROxfordEasyI2IRetrieval",
    "RP2kI2IRetrieval",
    "RParisEasyI2IRetrieval",
    "RT1T2VRetrieval",
    "ReMuQIT2TRetrieval",
    "RealMMRAGFinReportRetrieval",
    "RiaNewsRetrieval",
    "RuBQRetrieval",
    "RuSciBenchCiteRetrieval",
    "SCIDOCS",
    "SCIDOCS-NL",
    "SCIDOCS-PL",
    "SCIDOCS-VN",
    "SDSKoPubVDRT2IRetrieval",
    "SDSKoPubVDRT2ITRetrieval",
    "SHS100KA2ARetrieval",
    "SIQA",
    "SKQuadRetrieval",
    "SMESumRetrieval",
    "SNLRetrieval",
    "SOPI2IRetrieval",
    "SQuADKorV1Retrieval",
    "SSW60A2IRetrieval",
    "SWEbenchCodeRetrieval",
    "SadeemQuestionRetrieval",
    "SciFact",
    "SciFact-NL",
    "SciFact-PL",
    "SciFact-VN",
    "SciMMIRI2TRetrieval",
    "SciMMIRT2IRetrieval",
    "SeaVLCrawlingT2IRetrieval",
    "Shot2Story20KV2TRetrieval",
    "SketchyI2IRetrieval",
    "SlovakSumRetrieval",
    "SongDescriberT2ARetrieval",
    "SoundDescsA2TRetrieval",
    "SoundingEarthA2IRetrieval",
    "SpanishPassageRetrievalS2P",
    "SpanishPassageRetrievalS2S",
    "SpartQA",
    "SpeechCocoA2IRetrieval",
    "SpeechEditAcousticRetrieval",
    "SpokenCOCOA2IRetrieval",
    "SpokenSQuADT2ARetrieval",
    "SpokenWikipediaA2TRetrieval",
    "StackOverflowQA",
    "StanfordCarsI2IRetrieval",
    "StanfordI2VRetrieval",
    "StatcanDialogueDatasetRetrieval",
    "SweFaqRetrieval",
    "SwednRetrieval",
    "SynPerQARetrieval",
    "SyntecRetrieval",
    "SyntheticText2SQL",
    "T2Retrieval",
    "TRECCOVID",
    "TRECCOVID-NL",
    "TRECCOVID-PL",
    "TRECCOVID-VN",
    "TRECDL2019",
    "TUBerlinT2IRetrieval",
    "TUNABenchT2VRetrieval",
    "TUNABenchV2TRetrieval",
    "TV2Nordretrieval",
    "TVPLRetrieval",
    "TempReasonL1",
    "TempReasonL2Context",
    "TempReasonL2Fact",
    "TempReasonL2Pure",
    "TempReasonL3Context",
    "TempReasonL3Fact",
    "TempReasonL3Pure",
    "ToolRetrieval",
    "TopiOCQA",
    "Touche2020",
    "Touche2020-NL",
    "Touche2020-PL",
    "Touche2020-VN",
    "TurHistQuadRetrieval",
    "TwitterHjerneRetrieval",
    "UrbanSound8KA2TRetrieval",
    "VABBRetrieval",
    "VALOR32KV2TRetrieval",
    "VATEXV2TRetrieval",
    "VCDBCoreRetrieval",
    "VDRMultilingualRetrieval",
    "VGGSoundAVV2TRetrieval",
    "VQA2IT2TRetrieval",
    "VSC2022Retrieval",
    "VaaniA2TRetrieval",
    "Vidore2ESGReportsRetrieval",
    "Vidore3FinanceEnRetrieval",
    "VidoreArxivQARetrieval",
    "VieQuADRetrieval",
    "VimSketchA2ARetrieval",
    "VisRAGRetArxivQA",
    "VisRAGRetChartQA",
    "VisRAGRetInfoVQA",
    "VisRAGRetMPDocVQA",
    "VisRAGRetPlotQA",
    "VisRAGRetSlideVQA",
    "VisualNewsI2TRetrieval",
    "VisualNewsT2IRetrieval",
    "VizWizIT2TRetrieval",
    "WITT2IRetrieval",
    "WebFAQRetrieval",
    "WebQAT2ITRetrieval",
    "WebQAT2TRetrieval",
    "WebVidCoVRIT2VRetrieval",
    "WikiSQLRetrieval",
    "WikipediaRetrievalMultilingual",
    "WinoGrande",
    "XFlickr30kCoT2IRetrieval",
    "XM3600T2IRetrieval",
    "XMarket",
    "XPQARetrieval",
    "XQuADRetrieval",
    "YouCook2V2TRetrieval",
    "ZacLegalTextRetrieval",
    "bBSARDNLRetrieval",
    "corpus",
    "documents",
    "mMARCO-NL",
)

STS_TASKS: tuple[str, ...] = (
    "ATEC",
    "Assin2STS",
    "BIOSSES",
    "BIOSSES-VN",
    "FaroeseSTS",
    "Farsick",
    "FinParaSTS",
    "GermanSTSBenchmark",
    "HUMESICK-R",
    "HUMESTS12",
    "HUMESTS22",
    "HUMESTSBenchmark",
    "IndicCrosslingualSTS",
    "JSICK",
    "JSTS",
    "KLUE-STS",
    "KorSTS",
    "RUParaPhraserSTS",
    "RonSTS",
    "RuSTSBenchmarkSTS",
    "SICK-BR-STS",
    "SICK-NL-STS",
    "SICK-R",
    "SICK-R-PL",
    "SICK-R-VN",
    "SICKFr",
    "STS12",
    "STS12VisualSTS",
    "STS13",
    "STS13VisualSTS",
    "STS14",
    "STS14VisualSTS",
    "STS15",
    "STS15VisualSTS",
    "STS16",
    "STS16VisualSTS",
    "STS17",
    "STS17MultilingualVisualSTS",
    "STS22.v2",
    "STSBenchmark",
    "STSBenchmark-VN",
    "STSBenchmarkMultilingualSTS",
    "STSBenchmarkMultilingualVisualSTS",
    "STSES",
    "SemRel24STS",
    "SlovakSTS",
    "SlovakSumSTS",
    "UkrSedUASmallSTSv1",
)

RERANKING_TASKS: tuple[str, ...] = (
    "AlloprofReranking",
    "AskUbuntuDupQuestions",
    "AskUbuntuDupQuestions-VN",
    "BioVITAA2TReranking",
    "BuiltBenchReranking",
    "ColDeRReranking",
    "CorebC2TReranking",
    "ERESSReranking",
    "ESC50AudioReranking",
    "ESCIReranking",
    "FSDnoisy18kAudioReranking",
    "GTZANAudioReranking",
    "HUMECore17InstructionReranking",
    "HUMENews21InstructionReranking",
    "HUMERobust04InstructionReranking",
    "HUMEWikipediaRerankingMultilingual",
    "JQaRAReranking",
    "JQaRARerankingLite",
    "JaCWIRReranking",
    "JaCWIRRerankingLite",
    "LocBenchRR",
    "MIRACLReranking",
    "MVLSIBSent2Img",
    "MindSmallReranking",
    "MultiLongDocReranking",
    "MultiSWEbenchRR",
    "NamaaMrTydiReranking",
    "NevIR",
    "RuBQReranking",
    "SWEPolyBenchRR",
    "SWEbenchLiteRR",
    "SWEbenchMultilingualRR",
    "SWEbenchVerifiedRR",
    "SciDocsRR",
    "SciDocsRR-VN",
    "SkQuadReranking",
    "SlovakPharmacyDrMaxReranking",
    "StackOverflowDupQuestions",
    "StackOverflowDupQuestions-VN",
    "SyntecReranking",
    "T2Reranking",
    "UrbanSound8KAudioReranking",
    "VocalSoundAudioReranking",
    "VoyageMMarcoReranking",
    "WebLINXCandidatesReranking",
    "WikipediaRerankingMultilingual",
    "XGlueWPRReranking",
    "XModBenchAT2TReranking",
)


# --- Lookup ------------------------------------------------------------------

_FALLBACK_SUFFIXES: tuple[tuple[str, str], ...] = (
    ("Classification", "classification"),
    ("Reranking", "reranking"),
    ("Retrieval", "retrieval"),
    ("STS", "sts"),
)

# Hard-negatives eval variants (``X...HardNegatives``) score the same family
# as their base task, e.g. ``MIRACLRetrievalHardNegatives`` -> retrieval.
_HARD_NEGATIVES_SUFFIX = "HardNegatives"

_FALLBACK_PREFIXES: tuple[tuple[str, str], ...] = (("STS", "sts"),)

# ``*PairClassification`` is the pair-classification family (outside the four
# supported families) but would otherwise be swallowed by the
# ``Classification`` suffix rule below.
_EXCLUDED_SUFFIXES: tuple[str, ...] = ("PairClassification",)

# Names carried by historical ``mteb/results`` rows that newer mteb versions
# renamed (checked after the exact sets, before suffix fallback).
_LEGACY_ALIASES: dict[str, str] = {
    "MTOPIntent": "classification",  # renamed to MTOPIntentClassification
    "SciDocs": "retrieval",  # superseded by SciDocsRR / *Retrieval variants
    "CQADupstack": "retrieval",  # v1 aggregate of the CQADupstack*Retrieval tasks
    "Touche2021": "retrieval",  # exact sets only carry Touche2020 / Touche20xxRetrieval
    "Touche2022": "retrieval",
    "Touche2023": "retrieval",
    "SemRel": "sts",  # renamed to SemRel24STS
}

_EXACT: dict[str, str] = {}
for _names, _family in (
    (CLASSIFICATION_TASKS, "classification"),
    (RETRIEVAL_TASKS, "retrieval"),
    (STS_TASKS, "sts"),
    (RERANKING_TASKS, "reranking"),
):
    for _name in _names:
        _EXACT.setdefault(_name, _family)

# Case-folded view used only to resolve the base task of a ``*HardNegatives``
# variant (e.g. ``FeverHardNegatives`` -> ``FEVER``); unknown names must stay
# ``None``, so the main lookup remains case-sensitive.
_EXACT_CI: dict[str, str] = {_name.casefold(): _family for _name, _family in _EXACT.items()}


def task_family(task_name: str) -> str | None:
    """Map a raw ``mteb/results`` ``task_name`` to a family name, or ``None``.

    Families: ``classification``, ``retrieval``, ``sts``, ``reranking``.
    """
    family = _EXACT.get(task_name)
    if family is None:
        family = _LEGACY_ALIASES.get(task_name)
    if family is not None:
        return family
    for suffix in _EXCLUDED_SUFFIXES:
        if task_name.endswith(suffix):
            return None
    for suffix, family in _FALLBACK_SUFFIXES:
        if task_name.endswith(suffix):
            return family
    if task_name.endswith(_HARD_NEGATIVES_SUFFIX):
        base = task_name[: -len(_HARD_NEGATIVES_SUFFIX)]
        if base:
            return task_family(base) or _EXACT_CI.get(base.casefold())
    for prefix, family in _FALLBACK_PREFIXES:
        if task_name.startswith(prefix):
            return family
    return None
